name: trampolin-web
static_sites:
  - name: web
    github:
      repo: BrightOnAnalytics/trampolin-web
      branch: main
      deploy_on_push: true

    # Build command for static export
    build_command: |
      npm ci
      npm run build

      # Create output directory if it doesn't exist
      mkdir -p out

      # Copy static files
      cp -r public/. out/

    # Output directory for static files
    output_dir: out

    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: '1'
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}

    # HTTP settings
    http_port: 8080

    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 30

    # Error pages (optional)
    error_pages:
      - code: 404
        file: 404.html
