name: trampolin-web
services:
  - name: web
    github:
      repo: BrightOnAnalytics/trampolin-web
      branch: main
      deploy_on_push: true

    # Build command
    build_command: |
      npm ci
      npm run build

    # Run command for Next.js production server
    run_command: npm start

    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: '1'
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: DATABASE_CA_CERT
        value: ${DATABASE_CA_CERT}

    # HTTP settings
    http_port: 3000

    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30

    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs
