name: trampolin-web
services:
  - name: web
    github:
      repo: BrightOnAnalytics/trampolin-web
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    run_command: npm start
    envs:
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: NODE_ENV
        value: production
    health_check:
      http_path: /api/health
