name: trampolin-web
services:
  - name: web
    github:
      repo: BrightOnAnalytics/trampolin-web
      branch: main
      deploy_on_push: true
    build_command: |
      # Clean previous builds
      rm -rf .next/
      
      # Install all dependencies
      npm ci
      
      # Build the application with production settings
      NODE_ENV=production \
      NEXT_TELEMETRY_DISABLED=1 \
      next build
      
      # Prune dev dependencies after build
      npm prune --production
    run_command: next start -p $PORT
    envs:
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: NODE_ENV
        value: production
    health_check:
      http_path: /api/health
