name: trampolin-web
services:
  - name: web
    github:
      repo: BrightOnAnalytics/trampolin-web
      branch: main
      deploy_on_push: true
    build_command: |
      # Clean everything
      rm -rf .next/
      rm -rf node_modules/
      rm -rf .cache/
      
      # Install all dependencies
      npm ci
      
      # Build with production settings
      NODE_ENV=production \
      NEXT_TELEMETRY_DISABLED=1 \
      next build --no-lint
      
      # Clean up development dependencies after build
      npm prune --production
      
      # Clear Next.js cache and ensure proper permissions
      rm -rf .next/cache/
      chmod -R 755 .next
    run_command: |
      # Set Node.js options and environment variables
      export NODE_OPTIONS='--max-old-space-size=1024'
      export NODE_ENV=production
      
      # Start the Next.js application
      exec node node_modules/next/dist/bin/next start -p $PORT
    envs:
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: NODE_ENV
        value: production
    health_check:
      http_path: /api/health
