name: trampolin-web
services:
  - name: web
    github:
      repo: BrightOnAnalytics/trampolin-web
      branch: main
      deploy_on_push: true
    build_command: |
      # Clean everything
      rm -rf .next/
      rm -rf node_modules/.cache/
      
      # Install only production dependencies first
      npm ci --production=false
      
      # Build with production settings
      NODE_ENV=production \
      NEXT_TELEMETRY_DISABLED=1 \
      next build --no-lint
      
      # Clean up development dependencies
      npm prune --production
      
      # Clear Next.js cache
      rm -rf .next/cache/
    run_command: |
      NODE_OPTIONS='--max-old-space-size=1024' \
      NODE_ENV=production \
      next start -p $PORT
    envs:
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: NODE_ENV
        value: production
    health_check:
      http_path: /api/health
