name: trampolin-web
services:
  - name: web
    github:
      repo: BrightOnAnalytics/trampolin-web
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    envs:
      - key: NODE_ENV
        value: production
    health_check:
      http_path: /api/health
